export const scales: { [key: string]: string[] } = {
  'A minor': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  'A major': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
  'B flat minor': ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
  'B flat major': ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
  'B minor': ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
  'B major': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
  'C minor': ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
  'C major': ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
  'C# minor': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
  'C# major': ['C#', 'D#', 'F', 'F#', 'G#', 'A#', 'C'],
  'D flat minor': ['Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'B'],
  'D flat major': ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
  'D minor': ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
  'D major': ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
  'E flat minor': ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db'],
  'E flat major': ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
  'E minor': ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
  'E major': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
  'F minor': ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
  'F major': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
  'F# minor': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
  'F# major': ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'F'],
  'G flat minor': ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'Fb'],
  'G flat major': ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],
  'G minor': ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
  'G major': ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
  'G# minor': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
  'G# major': ['G#', 'A#', 'C', 'C#', 'D#', 'F', 'G'],
  'Ab minor': ['Ab', 'Bb', 'Cb', 'Db', 'Eb', 'Fb', 'Gb'],
  'Ab major': ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
};
